version: '2.1'

orbs:
  tests: 'govcms/tests@dev'

workflows:
  test:
    jobs:
      - tests/validate_composer
      - tests/drupal_practices
      - tests/build:
          requires:
            - tests/validate_composer
      - tests/basic:
          requires:
            - tests/build
      - tests/phpunit:
          requires:
            - tests/build
      - tests/cypress:
          requires:
            - tests/build
