version: 3
jobs:
  end-2-end:
    docker:
      - image: wodby/php:7.1
    steps:
      - checkout
      - run:
          name: Composer install
          command: composer install --prefer-dist --working-dir=build
      - run:
          name: Copy properties file into place
          command: cp build/phing/example.build.properties build/phing/build.properties
      - run:
          name: Phing build
          command: build/bin/phing -f build/phing/build.xml build
      - run:
          name: Build
          command: cat $DOCKER_USER
workflows:
  version: 2
  main:
    jobs:
      - end-2-end:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
